const BEATS = [
    {
        id: '1',
        dataID: '0',
        img: 'img/beats/1.png',
        title: 'mIPPO',
        date: '04.03.21',
        plays: '2,154',
        time: '2:41',
        url_track: 'https://beatmaker.tv/activeContent/freebeats//162662/KILL_BILL_163_bpm_prodharwit(beatmaker.TV).mp3',
    },
    {
        id: '2',
        dataID: '1',
        img: 'img/beats/2.png',
        title: 'RYADOM',
        date: '02.05.21',
        plays: '2,102',
        time: '3:11',
        url_track: 'https://beatmaker.tv/activeContent/freebeats//162662/Senorita(beatmaker.TV).mp3',
    },
    {
        id: '3',
        dataID: '2',
        img: 'img/beats/3.png',
        title: 'VOMNE',
        date: '03.07.20',
        plays: '2,084',
        time: '2:34',
        url_track: 'https://beatmaker.tv/activeContent/freebeats//129175/449(beatmaker.TV).mp3',
    },
    {
        id: '4',
        dataID: '3',
        img: 'img/beats/4.png',
        title: 'NABARE',
        date: '01.01.21',
        plays: '2,011',
        time: '2:55',
        url_track: 'https://beatmaker.tv/activeContent/freebeats//541888/drum_kit_demo(beatmaker.TV).mp3',
    },
    {
        id: '5',
        dataID: '4',
        img: 'img/beats/5.png',
        title: 'PRINCIP',
        date: '08.10.21',
        plays: '1,954',
        time: '1:56',
        url_track: 'https://beatmaker.tv/activeContent/freebeats//227669/target_drill2(beatmaker.TV).mp3',
    },
    {
        id: '6',
        dataID: '5',
        img: 'img/beats/6.png',
        title: 'Blunt',
        date: '05.06.21',
        plays: '1,894',
        time: '3:21',
        url_track: 'https://beatmaker.tv/activeContent/freebeats//129175/864(beatmaker.TV).mp3',
    },
    {
        id: '7',
        dataID: '6',
        img: 'img/beats/7.png',
        title: 'Fallen',
        date: '18.07.21',
        plays: '1,754',
        time: '3:33',
        url_track: 'https://beatmaker.tv/activeContent/freebeats//187582/Hype_Beat_Store__Free_Szhigayu_mosty_130_Bpm_Cmhypebeatstore_(beatmaker.TV).mp3',
    },
    {
        id: '8',
        dataID: '7',
        img: 'img/beats/8.png',
        title: 'Be cool',
        date: '30.09.21',
        plays: '1,589',
        time: '3:24',
        url_track: 'https://beatmaker.tv/activeContent/freebeats//159232/Up_to_Something(beatmaker.TV).mp3',
    },
]
